apiVersion: v1
kind: Service
metadata:
  name: traekfik-errors
  namespace: traefik
spec:
  selector:
    app: traekfik-errors
  ports:
  - name: traekfik-errors
    protocol: TCP
    port: 80
    targetPort: 80
